[build]
  command = "pnpm install && pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

# Favicon and manifest
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/x-icon"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https:;
      img-src 'self' https: data: blob:;
      script-src 'self' 'unsafe-inline' https:;
      style-src 'self' 'unsafe-inline' https:;
      font-src 'self' https: data:;
      connect-src 'self' https:;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(),
      interest-cohort=()
    """
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"